LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := GIFEngine
LOCAL_SRC_FILES:= libGIFEngine.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SHARED_LIBRARIES := GIFEngine
LOCAL_MODULE := gifmain
LOCAL_SRC_FILES :=gifcontrol.c
LOCAL_LDLIBS := -llog
include $(BUILD_SHARED_LIBRARY)
