/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_army_gifdemo_GifHandler */

#ifndef _Included_com_army_gifdemo_GifHandler
#define _Included_com_army_gifdemo_GifHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_army_gifdemo_GifHandler
 * Method:    openGif
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_army_gifdemo_GifHandler_openGif
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_army_gifdemo_GifHandler
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_army_gifdemo_GifHandler_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_army_gifdemo_GifHandler
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_army_gifdemo_GifHandler_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_army_gifdemo_GifHandler
 * Method:    renderFrame
 * Signature: (JLandroid/graphics/Bitmap;)J
 */
JNIEXPORT jlong JNICALL Java_com_army_gifdemo_GifHandler_renderFrame
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
